# Generated by Django 4.2.5 on 2023-09-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0)),
                ('type', models.CharField(default=0)),
                ('set', models.CharField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('color', models.CharField(default=0)),
                ('img', models.CharField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('blocker', models.BooleanField(default=False)),
                ('trigger', models.BooleanField(default=False)),
            ],
        ),
    ]
