# Generated by Django 4.2.5 on 2023-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='card1',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='card2',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='card3',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='card4',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='card5',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='card6',
            field=models.CharField(default=0),
        ),
    ]
