# Generated by Django 4.2.5 on 2023-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_deck_card1_deck_card2_deck_card3_deck_card4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='card',
            name='counter',
            field=models.IntegerField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='tekst', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card1',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card2',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card3',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card4',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card5',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card6',
            field=models.CharField(default='tekst'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
