# Generated by Django 4.2.5 on 2023-09-22 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_alter_card_color_alter_card_cost_alter_card_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='decklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=50),
        ),
    ]
