# Generated by Django 4.2.5 on 2023-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_remove_card_img_remove_deck_card1_remove_deck_card2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.CharField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='')),
                ('set', models.CharField(default='')),
                ('life', models.IntegerField(default='')),
                ('color1', models.CharField(default='Pure')),
                ('color2', models.CharField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(default='Donquixote Doflamingo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='counter',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default=''),
        ),
    ]
