# Generated by Django 4.2.5 on 2023-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_leader_deck_name_alter_card_color_alter_card_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='url',
            field=models.CharField(default=''),
        ),
    ]
