# Generated by Django 4.2.5 on 2024-05-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_leader_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='id',
            new_name='lp',
        ),
    ]
