# Generated by Django 4.2.5 on 2024-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_rename_id_leader_lp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='id',
            field=models.CharField(default=''),
        ),
    ]
