# Generated by Django 4.2.5 on 2023-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='')),
                ('type', models.CharField(default='')),
                ('set', models.CharField(default='')),
                ('cost', models.IntegerField(default='')),
                ('color', models.CharField(default='')),
                ('counter', models.IntegerField(default='')),
                ('blocker', models.BooleanField(default=False)),
                ('trigger', models.BooleanField(default=False)),
            ],
        ),
    ]
