# Generated by Django 4.2.5 on 2023-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_card_counter2k_alter_card_cost_alter_card_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default=''),
        ),
    ]
