# Generated by Django 4.2.5 on 2023-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='short_note',
            field=models.CharField(default='', max_length=30),
        ),
    ]
