# Generated by Django 4.2.5 on 2023-11-12 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_userinput_short_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='number_owned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2137)]),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='short_note',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
