# Generated by Django 4.2.5 on 2023-11-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
