# Generated by Django 4.2.5 on 2023-11-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_remove_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
