# Generated by Django 4.2.5 on 2023-11-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_card_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_path',
        ),
    ]
