# Generated by Django 4.2.5 on 2024-05-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_remove_card_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id',
            new_name='lp',
        ),
    ]
