# Generated by Django 4.2.5 on 2024-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_rename_id_card_lp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='id',
            field=models.CharField(default=''),
        ),
    ]
