# Generated by Django 4.2.5 on 2024-05-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id',
            new_name='idx',
        ),
    ]
