# Generated by Django 4.2.5 on 2023-11-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_rename_color_userpreference_leader1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='leader1',
            new_name='leader',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='leader2',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='leader3',
        ),
    ]
